# Generated by Django 5.0.4 on 2024-04-19 20:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(max_length=220, validators=[django.core.validators.RegexValidator(code='invalid_address', message='Direccion', regex='^[a-zA-Z0-9!@#$&()\\(\\)\\(/)]')]),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='web',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_web_address', message='Web', regex='^[a-zA-Z0-9!@#$&()\\(\\)\\(/)]')]),
        ),
        migrations.CreateModel(
            name='LicitanteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.empresa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
