# Generated by Django 5.0.4 on 2024-04-22 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licitacion',
            options={'permissions': [('can_view_licitaciones_from_my_company', 'Can view only licitaciones that belong to user company')], 'verbose_name': 'licitacion', 'verbose_name_plural': 'licitaciones'},
        ),
    ]
