# Generated by Django 5.0.4 on 2024-04-28 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0004_alter_licitacion_owner'),
        ('ofertas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertaitem',
            name='licitacion_item',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='licitaciones.licitacionitem'),
            preserve_default=False,
        ),
    ]
