# Generated by Django 5.0.4 on 2024-04-28 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0004_alter_licitacion_owner'),
        ('ofertas', '0002_ofertaitem_licitacion_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='licitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitaciones.licitacion'),
        ),
    ]
