# Generated by Django 5.0.4 on 2024-04-28 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0004_alter_licitacion_owner'),
        ('ofertas', '0003_alter_oferta_licitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertaitem',
            name='licitacion_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitaciones.licitacionitem'),
        ),
    ]
